
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLOSE_BRACE CLOSE_PAREN DOT EQUAL FOR ID INT LESS_EQUAL NUMBER OPEN_BRACE OPEN_PAREN PLUS PLUSPLUS PRINTLN SEMICOLON STRINGprogram : statementstatement : for_loop\n                 | print_statementfor_loop : FOR OPEN_PAREN INT ID EQUAL NUMBER SEMICOLON ID LESS_EQUAL NUMBER SEMICOLON ID PLUSPLUS CLOSE_PAREN OPEN_BRACE print_statement CLOSE_BRACEprint_statement : ID DOT ID DOT PRINTLN OPEN_PAREN STRING PLUS ID CLOSE_PAREN SEMICOLON'
    
_lr_action_items = {'FOR':([0,],[5,]),'ID':([0,8,9,17,20,25,30,],[6,10,11,19,22,27,6,]),'$end':([1,2,3,4,26,32,],[0,-1,-2,-3,-5,-4,]),'OPEN_PAREN':([5,14,],[7,16,]),'DOT':([6,10,],[8,12,]),'INT':([7,],[9,]),'EQUAL':([11,],[13,]),'PRINTLN':([12,],[14,]),'NUMBER':([13,21,],[15,23,]),'SEMICOLON':([15,23,24,],[17,25,26,]),'STRING':([16,],[18,]),'PLUS':([18,],[20,]),'LESS_EQUAL':([19,],[21,]),'CLOSE_PAREN':([22,28,],[24,29,]),'CLOSE_BRACE':([26,31,],[-5,32,]),'PLUSPLUS':([27,],[28,]),'OPEN_BRACE':([29,],[30,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement':([0,],[2,]),'for_loop':([0,],[3,]),'print_statement':([0,30,],[4,31,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement','program',1,'p_program','app.py',68),
  ('statement -> for_loop','statement',1,'p_statement','app.py',73),
  ('statement -> print_statement','statement',1,'p_statement','app.py',74),
  ('for_loop -> FOR OPEN_PAREN INT ID EQUAL NUMBER SEMICOLON ID LESS_EQUAL NUMBER SEMICOLON ID PLUSPLUS CLOSE_PAREN OPEN_BRACE print_statement CLOSE_BRACE','for_loop',17,'p_for_loop','app.py',78),
  ('print_statement -> ID DOT ID DOT PRINTLN OPEN_PAREN STRING PLUS ID CLOSE_PAREN SEMICOLON','print_statement',11,'p_print_statement','app.py',83),
]
